export const classLabels = {
    rage_count: "Rage Count",
    rage_damage_bonus: "Rage Damage Bonus",
    brutal_critical_dice: "Brutal Critical Dice",
    bardic_inspiration_die: "Bardic Inspiration: 1d",
    song_of_rest_die: "Song of Rest: 1d",
    magical_secrets_max_5: "Magical Secrets - max spell level 5",
    magical_secrets_max_7: "Magical Secrets - max spell level 7",
    magical_secrets_max_9: "Magical Secrets - max spell level 9",
    cantrips_known: "Cantrips known",
    spells_known: "Spells known",
    spell_slots_level_1: "Level 1 spell slots",
    spell_slots_level_2: "Level 2 spell slots",
    spell_slots_level_3: "Level 3 spell slots",
    spell_slots_level_4: "Level 4 spell slots",
    spell_slots_level_5: "Level 5 spell slots",
    spell_slots_level_6: "Level 6 spell slots",
    spell_slots_level_7: "Level 7 spell slots",
    spell_slots_level_8: "Level 8 spell slots",
    spell_slots_level_9: "Level 9 spell slots",
    martial_arts: "Martial Arts",
    channel_divinity_charges: "Channel Divinity charges",
    destroy_undead_cr: "Destroy Undead(Cr)",
    wild_shape_max_cr: "Wild Shape (CR)",
    wild_shape_swim: "Wild Shape Swim",
    wild_shape_fly: "Wild Shape Fly",
    action_surges: "Action Surges",
    indomitable_uses: "Indomitable Uses",
    extra_attacks: "Extra Attacks",
    sneak_attack: "Sneak Attack",
    ki_points: "Ki Points",
    unarmored_movement: "Unarmored Movement Bonus Speed",
    aura_range: "Aura Range (ft)",
    favored_enemies: "Favored Enemies",
    favored_terrain: "Favored Terrain",
    sorcery_points: "Sorcery Points",
    metamagic_known: "Metamagic known",
    spell_slot_level: "spell slot level",
    sorcery_point_cost: "Sorcery Point Cost",
    invocations_known: "Invocations Known",
    mystic_arcanum_level_6: "Mystic Arcanum spell level 6",
    mystic_arcanum_level_7: "Mystic Arcanum spell level 7",
    mystic_arcanum_level_8: "Mystic Arcanum spell level 8",
    mystic_arcanum_level_9: "Mystic Arcanum spell level 9",
    arcane_recovery_levels: "Arcane Recovery Levels",
    creating_spell_slots: "Creating Spell Slots",
  };